### ISSUE TITLE
KuCoin l2snapshot and l2update don't include sequenceId so it's not possible to ensure correct data

### ISSUE THREAD

**Issue by evan-coygo** [altangent/ccxws#164]
**Exchange**
KuCoin

**Subscription type**
Level2 orderbook updates

**Describe the bug**
The KuCoin REST API for the orderbook snapshot, and the websocket feed for l2 updates, both include sequence info that ccxws isn't propagating. Often when subscribing via ccxws, you'll get a couple l2update events before the l2snapshot event, and it's not possible to know when to apply the l2updates so you can't be sure that the data is correct when maintaining a local order book.

**To Reproduce**
1. Subscribe to Level 2 updates on KuCoin market, for example ETH-BTC
2. You'll get a few l2update events
3. You'll get a l2snapshot shortly after
4. You don't know if the first few l2updates before the l2snapshot should be ignored, or applied to the l2snapshot

**Expected behavior**
Sequence ID is included in the l2update and l2snapshot event payloads from ccxws, since they are included in the KuCoin API payloads.

**Comment by bmancini55** [comment]
Thanks for reporting the issue!

After a quick look of the documentation: https://docs.kucoin.com/#level-2-market-data, it looks like updates have similar behavior to Binance.  To resolve this, the following changes will need to be made:

- update `_processL2Update`
  -  add `sequenceId`, `sequenceIdLast` properties from the WS update stream
  - remove `timestampMs` since it no longer provides value
- update `_requestLevel2Snapshot`
   - include `sequenceId`
- update tests suite to indicate it no longer supports `timestampMs` but now supports `sequenceId`

**Comment by bmancini55** [comment]
This has been released in v0.35.0, thanks!

**Comment by evan-coygo** [comment]
thanks for the quick fix :+1:

**Comment by evan-coygo** [comment]
@bmancini55 this may have introduced a bug, after upgrading from 0.34.1 to 0.35.0 I see this error now 

```
 TypeError: this._handle.unref is not a function

      at Throttle._schedule (node_modules/ccxws/src/flowcontrol/throttle.js:27:18)
      at Throttle._process (node_modules/ccxws/src/flowcontrol/throttle.js:35:12)
      at Throttle.add (node_modules/ccxws/src/flowcontrol/throttle.js:12:29)
      at _sem.take (node_modules/ccxws/src/exchanges/kucoin-client.js:171:12)
      at item.task (node_modules/semaphore/lib/semaphore.js:40:29)
```

at this line in `node_modules/ccxws/src/flowcontrol/throttle.js`
```
 _schedule() {
    this._handle = setTimeout(this._process.bind(this), this.delayMs);
    this._handle.unref();   // <--- here
  }
```

**Comment by bmancini55** [comment]
Thanks, will add a conditional check and get an update out shortly.

unref was added in 0.9.1 (https://nodejs.org/api/timers.html#timers_timeout_unref). What version of node did this happen with?

**Comment by evan-coygo** [comment]
node v8.11.4

**Comment by bmancini55** [comment]
Cool, thanks!  Just wanted to make sure there wasn’t a bigger issue

**Comment by bmancini55** [comment]
@evan-coygo should be fixed in v0.35.1.  Let me know if you encounter any other problems!
